### ISSUE TITLE
动态绑定问题

### ISSUE THREAD

**Issue by MeiVinEight** [MeiVinEight/ReflectionFX#6]
动态绑定用invokespecial调用方法会报错

MethodKind implementation = new MethodKind("hashCode", int.class, Object.class);
MethodKind invocation = new MethodKind("hashCode", int.class);
int kind = ReflectionFactory.KIND_INVOKE_SPECIAL;
SimpleObject object = new ReflectionFactory(SimpleObject.class, Object.class).method(implementation, invocation, kind).allocate(); System.out.println(object.hashCode(new Object()));

SimpleObject的定义
public interface SimpleObject
{
	int hashCode(Object obj);
}

Exception in thread "main" java.lang.IllegalAccessError: Receiver class java/lang/Object must be the current class or a subtype of interface SimpleObject at Main.main(Main.java:12)

尝试在define之前把字节码保存到文件然后读取文件加载不会报错

**Comment by MeiVinEight** [comment]
动态绑定用invokespecial调用方法会报错

MethodKind implementation = new MethodKind("hashCode", int.class, Object.class);
MethodKind invocation = new MethodKind("hashCode", int.class);
int kind = ReflectionFactory.KIND_INVOKE_SPECIAL;
SimpleObject object = new ReflectionFactory(SimpleObject.class, Object.class).method(implementation, invocation, kind).allocate(); System.out.println(object.hashCode(new Object()));

SimpleObject的定义
public interface SimpleObject
{
	int hashCode(Object obj);
}


Exception in thread "main" java.lang.IllegalAccessError: Receiver class java/lang/Object must be the current class or a subtype of interface SimpleObject at Main.main(Main.java:12)

尝试在define之前把字节码保存到文件然后读取文件加载不会报错

**Comment by MeiVinEight** [comment]
已解决
